title: Issie's knowledge base
description: DevOps、Network、Safe
remote_theme: pages-themes/architect@v0.2.0
plugins:
  - jekyll-remote-theme
show_downloads: false # 是否展示下载
google_analytics: true # 谷歌分析开启